import { readFile, readdir, stat } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { ASSETS_DIR, CONTENT_DIR } from './globals';

/**
 * Bundled fallback: src/lib/assets/ inside the SvelteKit project.
 * Always available; used when ASSETS_DIR doesn't have the file.
 */
const BUNDLED_ASSETS_DIR = resolve(process.cwd(), 'src/lib/assets');

/**
 * Read a named asset file from the given directory.
 *
 * @param name       Filename, e.g. "mundus-map.svg". No path separators allowed.
 * @param assetsDir  Directory to read from.
 * @returns          File contents as a UTF-8 string, or null if not found.
 * @throws           On a name that looks like a path traversal attempt.
 */
export async function readAsset(name: string, assetsDir: string): Promise<string | null> {
	if (name.includes('/') || name.includes('\\') || name.includes('..')) {
		throw new Error(`readAsset: invalid asset name "${name}"`);
	}
	const path = resolve(assetsDir, name);
	try {
		const st = await stat(path);
		if (!st.isFile()) return null;
		return await readFile(path, 'utf-8');
	} catch {
		return null;
	}
}

/**
 * In-memory asset cache singleton.
 *
 * Reads from ASSETS_DIR first (the external world dir's assets/ when
 * BUNNYTRAIL_WORLD_DIR is configured), with a transparent fallback to the
 * bundled src/lib/assets/ if the file isn't found there. This means the
 * bundled file is always available during development even before the
 * external assets directory has been populated.
 *
 * The dev watcher calls `assets.invalidate(name)` when a file in ASSETS_DIR
 * changes, so the next request re-reads from disk.
 *
 * In production the cache is never invalidated; assets are read once and held
 * for the lifetime of the process.
 */
/**
 * Synthetic entry: when requested, this name is auto-generated by
 * concatenating every CSS file that has a sibling SVG of the same
 * basename. Worlds don't ship this file on disk; the engine
 * fabricates it so adding a new map is "drop foo.svg + foo.css"
 * with no manifest to maintain.
 */
const INLINE_SVG_BUNDLE = 'inline-svg.css';

class AssetCache {
	#cache = new Map<string, string>();

	/**
	 * Return the cached content for `name`, reading from disk on the first
	 * access or after invalidation. Falls back to the bundled copy if the
	 * primary ASSETS_DIR doesn't have the file.
	 *
	 * The special name `inline-svg.css` is synthesised: it concatenates
	 * every `<base>.css` paired with a `<base>.svg` in the assets dir.
	 * Disk copies are ignored so worlds don't need a shell file.
	 */
	async get(name: string): Promise<string | null> {
		if (this.#cache.has(name)) {
			// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
			return this.#cache.get(name)!;
		}

		if (name === INLINE_SVG_BUNDLE) {
			const bundled = await this.#buildInlineSvgBundle();
			this.#cache.set(name, bundled);
			return bundled;
		}

		// Try primary location first.
		let content = await readAsset(name, ASSETS_DIR);

		// Fall back to bundled copy if the primary location didn't have it
		// (e.g. BUNNYTRAIL_WORLD_DIR is set but assets/ hasn't been populated yet).
		if (content === null && ASSETS_DIR !== BUNDLED_ASSETS_DIR) {
			content = await readAsset(name, BUNDLED_ASSETS_DIR);
		}

		if (content !== null) this.#cache.set(name, content);
		return content;
	}

	/**
	 * Evict one entry so the next `get` re-reads from disk. Any CSS
	 * change also evicts the synthesised inline-svg bundle so it
	 * gets rebuilt with the latest contents on the next request.
	 */
	invalidate(name: string): void {
		this.#cache.delete(name);
		if (name.toLowerCase().endsWith('.css') || name.toLowerCase().endsWith('.svg')) {
			this.#cache.delete(INLINE_SVG_BUNDLE);
		}
	}

	/** Evict all entries. */
	invalidateAll(): void {
		this.#cache.clear();
	}

	/**
	 * Enumerate the union of asset filenames available across the
	 * configured ASSETS_DIR and the bundled fallback. Used by the
	 * /api/assets/[name] handler's prerender entries() so every
	 * static asset becomes a real file in the build output instead
	 * of relying on a serverless function (which adapter-vercel
	 * can't satisfy because the assets dir isn't bundled into the
	 * function's filesystem).
	 *
	 * Duplicates are de-duped; primary dir wins over fallback.
	 * Missing dirs are silently treated as empty.
	 */
	async names(): Promise<string[]> {
		const seen = new Set<string>();
		for (const dir of [ASSETS_DIR, BUNDLED_ASSETS_DIR]) {
			if (dir === ASSETS_DIR && dir === BUNDLED_ASSETS_DIR && seen.size > 0) break;
			try {
				const entries = await readdir(dir, { withFileTypes: true });
				for (const e of entries) {
					if (e.isFile()) seen.add(e.name);
				}
			} catch {
				// Dir doesn't exist — fine.
			}
		}
		// Synthetic bundle is always available even when no file
		// exists on disk, so the prerenderer emits it.
		seen.add(INLINE_SVG_BUNDLE);
		return [...seen];
	}

	/**
	 * Build the synthetic inline-svg.css bundle: every `<base>.css`
	 * whose `<base>.svg` sibling exists, concatenated in stable
	 * (alphabetical) order. Each file's rules are wrapped in
	 * `.bt-inline-svg--<base> { ... }` via native CSS nesting so
	 * they apply only inside the matching figure (the engine emits
	 * `class="bt-inline-svg bt-inline-svg--<base>"` per figure).
	 * World authors don't need manual scoping selectors and CSS
	 * from one map can't bleed into another.
	 *
	 * If a world genuinely needs to share rules across figures, it
	 * can put unscoped rules in a CSS file with no SVG sibling and
	 * `@import` it from the per-figure files itself — the engine
	 * stays out of that decision.
	 *
	 * Any disk-resident `inline-svg.css` is intentionally ignored —
	 * the synthesised bundle is the only source of truth and the
	 * whole point is that worlds don't ship a shell file.
	 */
	async #buildInlineSvgBundle(): Promise<string> {
		const all = await this.names();
		const svgs = new Set(
			all.filter((n) => n.toLowerCase().endsWith('.svg')).map((n) => n.slice(0, -4))
		);
		const paired = all
			.filter((n) => {
				if (!n.toLowerCase().endsWith('.css')) return false;
				if (n === INLINE_SVG_BUNDLE) return false;
				const base = n.slice(0, -4);
				if (!svgs.has(base)) return false;
				// Only CSS-class-safe basenames get auto-scoped; anything
				// else is skipped rather than producing broken selectors.
				return /^[A-Za-z0-9_-]+$/.test(base);
			})
			.sort();

		const parts: string[] = [
			'/* Auto-generated by bunnytrail: each <name>.css next to a',
			'   <name>.svg in the world assets dir or content tree is',
			'   wrapped here in .bt-inline-svg--<name> { ... } so its',
			'   rules only apply inside the matching figure.',
			"   Don't edit this URL's body directly — edit the per-map",
			'   CSS files. */',
			''
		];
		for (const name of paired) {
			const css = await this.get(name);
			if (css === null) continue;
			const base = name.slice(0, -4);
			parts.push(
				`/* === ${name} (assets/) === */`,
				`.bt-inline-svg--${base} {`,
				css.trimEnd(),
				'}',
				''
			);
		}

		// Also include SVG+CSS pairs co-located in the content tree.
		// These are authored as siblings of entity index files (e.g.
		// content/foundation/fabric/primitives/mundus/mundus-map.svg +
		// mundus-map.css). We walk CONTENT_DIR recursively, collecting
		// pairs whose basename is CSS-class-safe and hasn't already been
		// provided by the assets/ dir above.
		const pairedBases = new Set(paired.map((n) => n.slice(0, -4)));
		const contentPairs = await collectContentSvgCssPairs(CONTENT_DIR, pairedBases);
		for (const { base, cssPath } of contentPairs) {
			let css: string;
			try {
				css = await readFile(cssPath, 'utf-8');
			} catch {
				continue;
			}
			parts.push(
				`/* === ${base}.css (content/) === */`,
				`.bt-inline-svg--${base} {`,
				css.trimEnd(),
				'}',
				''
			);
		}

		return parts.join('\n');
	}
}

export const assets = new AssetCache();

/**
 * Recursively walk `dir`, collecting `{ base, cssPath }` entries for
 * every `<base>.css` that has a sibling `<base>.svg` in the same
 * folder and whose `base` is a CSS-class-safe identifier
 * (`[A-Za-z0-9_-]+`).
 *
 * `alreadyCovered` is the set of basenames already included from the
 * assets/ directory — those are skipped to avoid duplicate rules in
 * the bundle (assets/ takes priority over content/).
 *
 * This is intentionally a best-effort scan: directory read errors are
 * silently swallowed so a missing or unreadable folder never breaks
 * the bundle build for the rest of the world.
 */
async function collectContentSvgCssPairs(
	dir: string,
	alreadyCovered: ReadonlySet<string>
): Promise<Array<{ base: string; cssPath: string }>> {
	const results: Array<{ base: string; cssPath: string }> = [];
	await walkDir(dir, alreadyCovered, results);
	// Stable sort by base name so the bundle output is deterministic.
	results.sort((a, b) => a.base.localeCompare(b.base));
	return results;
}

async function walkDir(
	dir: string,
	alreadyCovered: ReadonlySet<string>,
	results: Array<{ base: string; cssPath: string }>
): Promise<void> {
	let entries;
	try {
		entries = await readdir(dir, { withFileTypes: true });
	} catch {
		return;
	}

	// Collect filenames in this directory.
	const fileNames = new Set(entries.filter((e) => e.isFile()).map((e) => e.name));

	for (const name of fileNames) {
		if (!name.toLowerCase().endsWith('.css')) continue;
		const base = name.slice(0, -4);
		if (!base) continue;
		// Skip if already provided by assets/ dir.
		if (alreadyCovered.has(base)) continue;
		// Only CSS-class-safe basenames.
		if (!/^[A-Za-z0-9_-]+$/.test(base)) continue;
		// Must have a sibling SVG.
		if (!fileNames.has(`${base}.svg`) && !fileNames.has(`${base}.SVG`)) continue;
		results.push({ base, cssPath: join(dir, name) });
	}

	// Recurse into subdirectories.
	for (const entry of entries) {
		if (entry.isDirectory()) {
			await walkDir(join(dir, entry.name), alreadyCovered, results);
		}
	}
}
